# Generated by Django 5.2 on 2025-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_cuisine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/'),
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
