# Generated by Django 5.2 on 2025-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantphoto_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantphoto',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(upload_to='restaurant_photos/'),
        ),
    ]
