# Generated by Django 5.2 on 2025-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurantphoto_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/'),
        ),
    ]
