# Generated by Django 5.2 on 2025-05-06 19:04

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurantphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(upload_to=restaurants.models.restaurant_photo_path),
        ),
    ]
