# Generated by Django 5.2 on 2025-05-06 19:06

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_image_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.restaurant_photo_path),
        ),
    ]
